name: react Build

on: 
    push:
    workflow_dispatch:

jobs: 
    build_test:
      name: build_test
      runs-on: ubuntu-latest
      steps: 
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: "22"
        - name: Install dependencies
          run: npm install
        - name: Run build
          run: npm run build
